### PR TITLE
Update command.rb.tt

### PR DESCRIPTION
**Pull request by vaporyhumo**
### Describe the change
It fixes a typo in a `Command` template.

### Why are we doing this?
Just found it and thought I might fix it.

### Benefits
It will have better documentation.

### Drawbacks
None.

### Requirements
Put an X between brackets on each line if you have done the item:
[] Tests written & passing locally?
[x] Code style checked?
[x] Rebased with `master` branch?
[] Documentaion updated?

### CODE REVIEW

**Comment by vaporyhumo** [comment]
Please point me out if there is something else I should be updating. I haven't checked specs since I wouldn't expect them to also have the typo but yeah... Just let me know if anything.

**Comment by vaporyhumo** [comment]
Well, specs did have the typo too so I also updated them :)

**Comment by piotrmurach** [comment]
Thanks ❤️

**Comment by vaporyhumo** [comment]
No prob, thanks to you too, I'm enjoying using this to make my own gem so, yeah thanks!

**Pull request merged**
